---
#- name: Get VOMS client packages based on OS
#  include_vars:
#    dir: vars
#    files_matching: "{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yml"
#    name: os_vars
#  tags:
#    - testing
#    - all

# Firewalld has been disbled : FIXME, maybe not?
#- include_tasks: firewall.yml

# FIXME: It seems that daemons are not restarted on configuration changes

- name: arc_frontend_griddir must be defined
  assert:
    that: "arc_frontend_griddir is defined"

- name: arc_frontend_sessiondir must be defined
  assert:
    that: "arc_frontend_sessiondir is defined"

- name: install Nordugrid ARC packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ arc_frontend_packages | default({}) }}"

- name: Create Grid dir 
  file:
    path: "{{ arc_frontend_griddir }}"
    state: directory
    owner: root
    mode: 0755

- name: Create Session dir 
  file:
    path: "{{ arc_frontend_sessiondir }}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0755

- name: Create Control dir 
  file:
    path: "{{ arc_frontend_controldir }}"
    state: directory

- name: Create arc pool directories
  file:
    path: "{{ grid_security_dir }}/pools/{{ item }}"
    state: directory
  loop: "{{ supported_vos }}"

- name: Create arc pool file for main vos
  template:
    src: "pool_vo.j2"
    dest: "{{ grid_security_dir }}/pools/{{ item.name }}/pool"
  loop: "{{ supported_vos_data_list }}"

- name: Create arc vo roles pools directories
  file:
    path: "{{ grid_security_dir }}/pools/{{ item.0.account_prefix }}{{ item.1.suffix }}"
    state: directory
  loop: "{{ supported_vos_data_list | subelements('voms_mappings', 'skip_missing=True') }}"

- name: Create arc vo roles pools files
  template:
    src: "pool.j2"
    dest: "{{ grid_security_dir }}/pools/{{ item.0.account_prefix }}{{ item.1.suffix }}/pool"
  loop: "{{ supported_vos_data_list | subelements('voms_mappings', 'skip_missing=True') }}"

- name: Create nordugridmap vo roles mapping
  template:
    src: "role-mapping.j2"
    dest: "{{ grid_security_dir }}/nordugrid-vo-mappings/{{ vo.name }}-role-mapping"
    owner: root
    mode: 0644
  loop: "{{ supported_vos_data_list }}"
  loop_control:
    loop_var: "vo"
  
- name: Template arc.conf file
  template:
    backup: yes
    src: "arc{{ arc_version }}.conf.j2"
    dest: /etc/arc.conf
    owner: root
    mode: 0644
  notify:
    - "restart arc"

- name: start and enable arc frontend services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ arc_frontend_services[arc_version] | default({}) }}"

# Starts BDII service: FIXME: likely not needed.
- name: start and enable arc bdii service
  service:
    name: bdii
    state: started
    enabled: yes

# Run handlers
- meta: flush_handlers

#- name: Validate a-rex service
#  shell: /etc/init.d/a-rex validate

# FIXME: Removed test block, may add it back in the future