---
#- name: Get VOMS client packages based on OS
#  include_vars:
#    dir: vars
#    files_matching: "{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yml"
#    name: os_vars
#  tags:
#    - testing
#    - all

# Firewalld has been disbled : FIXME, maybe not?
#- include_tasks: firewall.yml

# FIXME: It seems that daemons are not restarted on configuration changes

- name: arc_frontend_griddir must be defined
  assert:
    that: "arc_frontend_griddir is defined"

- name: arc_frontend_sessiondir must be defined
  assert:
    that: "arc_frontend_sessiondir is defined"

# Remove old arc packages
- name: Remove old arc packages
  package:
    name: "nordugrid-arc{{ arc_version - 1 }}*"
    state: removed

- name: install Nordugrid ARC packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ arc_frontend_packages[arc_version] | default({}) }}"

# At start a script test that arc config is correct.
# Unfortunately, the script: /usr/libexec/arc/arc-config-check is
# trying to access  europe.pool.ntp.org which cannot be reached.
# The occurences of europe.pool.ntp.org have to be changed
# to the content of grid_ntp_server" variable.
#- name: Fix NTP server in arc.conf
#  replace:
#    path:  /usr/libexec/arc/arc-config-check
#    regexp: '(.*)europe.pool.ntp.org(.*)'
#    replace: '\1{{ grid_ntpd_server }}\2'

# The following files should be removed:
# /etc/arc.conf.d/00-testCA-hostcert.conf
# /etc/arc.conf.d/10-testCA-access.conf
- name: Remove test certificates config
  file:
    path: "/etc/arc.conf.d/00-testCA-hostcert.conf"
    state: absent
- name: Remove test certificates access
  file:
    path: "/etc/arc.conf.d/10-testCA-access.conf"
    state: absent

- name: Create Grid dir 
  file:
    path: "{{ arc_frontend_griddir }}"
    state: directory
    owner: root
    mode: 0755

- name: Create Session dir 
  file:
    path: "{{ arc_frontend_sessiondir }}"
    state: directory
    owner: nobody
    group: nobody
    mode: 0755

- name: Create Control dir 
  file:
    path: "{{ arc_frontend_controldir }}"
    state: directory

- name: Create arc pool directories
  file:
    path: "{{ gridsite_grid_security_dir }}/pools/{{ item }}"
    state: directory
  loop: "{{ gridsite_supported_vos }}"

- name: Create arc pool file for main vos
  template:
    src: "pool_vo.j2"
    dest: "{{ gridsite_grid_security_dir }}/pools/{{ item.name }}/pool"
  loop: "{{ gridsite_supported_vos_data_list }}"

- name: Create arc vo roles pools directories
  file:
    path: "{{ gridsite_grid_security_dir }}/pools/{{ item.1.group }}"
    state: directory
  loop: "{{ gridsite_supported_vos_data_list | subelements('roles', 'skip_missing=True') }}"

- name: Create arc vo roles pools files
  template:
    src: "pool.j2"
    dest: "{{ gridsite_grid_security_dir }}/pools/{{ item.1.group }}/pool"
  loop: "{{ gridsite_supported_vos_data_list | subelements('roles', 'skip_missing=True') }}"
  
- name: Template arc.conf file
  template:
    backup: yes
    src: "arc{{ arc_version }}.conf.j2"
    dest: /etc/arc.conf
    owner: root
    mode: 0644
  notify:
    - "restart arc"

- name: start and enable arc frontend services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ arc_frontend_services[arc_version] | default({}) }}"

# Starts BDII service: FIXME: likely not needed.
- name: start and enable arc bdii service
  service:
    name: bdii
    state: started
    enabled: yes

# Add ENV/PROXY to arc.conf
- name: Flag ENV/PROXY in arc
  command: arcctl rte enable ENV/PROXY

# Add ENV/GLITE to arc.conf
- name: Flag ENV/GLITE in arc
  command: arcctl rte enable ENV/GLITE --dummy

# Run handlers
- meta: flush_handlers

#- name: Validate a-rex service
#  shell: /etc/init.d/a-rex validate

# FIXME: Removed test block, may add it back in the future
